# cuestionarios.py

cuestionarios = {
    "Infraestructura": [
        {"pregunta": "¿El cableado estructurado está canalizado?", "tipo": "si_no"},
        {"pregunta": "¿Existen canaletas o ductos para cableado?", "tipo": "si_no"},
        {"pregunta": "¿Existen UPS funcionando para respaldo eléctrico?", "tipo": "si_no"},
        {"pregunta": "Cantidad de tomas eléctricas por estación de trabajo", "tipo": "numero"},
        {"pregunta": "¿Existe plan de mantenimiento eléctrico?", "tipo": "si_no"},
        {"pregunta": "¿Se identifican adecuadamente los puntos de red?", "tipo": "si_no"},
        {"pregunta": "Evalúe la organización del cableado estructurado", "tipo": "escala"},
        {"pregunta": "¿Existen sistemas de puesta a tierra?", "tipo": "si_no"},
        {"pregunta": "¿Los cables de red están expuestos?", "tipo": "si_no"},
        {"pregunta": "¿Hay evidencia de sobrecarga eléctrica?", "tipo": "si_no"},
        {"pregunta": "Señale el estado de las canaletas visibles", "tipo": "multiple", "opciones": ["Buen estado", "Regular", "Mal estado"]},
        {"pregunta": "¿Se dispone de planos de red?", "tipo": "si_no"},
        {"pregunta": "¿El sistema eléctrico fue inspeccionado el último año?", "tipo": "si_no"},
        {"pregunta": "Cantidad de switches en funcionamiento", "tipo": "numero"},
        {"pregunta": "¿Los switches están organizados en un rack?", "tipo": "si_no"},
        {"pregunta": "¿Existen puntos de acceso inalámbricos?", "tipo": "si_no"},
        {"pregunta": "Evalúe la cobertura de red en el laboratorio", "tipo": "escala"},
        {"pregunta": "¿Se realiza limpieza de equipos de red periódicamente?", "tipo": "si_no"},
        {"pregunta": "¿Las fuentes de energía están etiquetadas?", "tipo": "si_no"},
        {"pregunta": "¿Existen interruptores diferenciales?", "tipo": "si_no"},
        {"pregunta": "¿Hay tomas de corriente aterrizadas?", "tipo": "si_no"},
        {"pregunta": "¿El laboratorio cuenta con pararrayos?", "tipo": "si_no"},
        {"pregunta": "¿Hay ventilación en las áreas donde están los switches?", "tipo": "si_no"},
        {"pregunta": "¿Las extensiones eléctricas están permitidas?", "tipo": "si_no"},
        {"pregunta": "¿Los sistemas eléctricos cumplen normativa nacional?", "tipo": "si_no"},
        {"pregunta": "¿Existe documentación técnica del cableado?", "tipo": "si_no"},
        {"pregunta": "¿El laboratorio cuenta con una red redundante?", "tipo": "si_no"},
        {"pregunta": "¿Se utilizan etiquetas para diferenciar puertos?", "tipo": "si_no"},
        {"pregunta": "¿Hay evidencia de reparación reciente en infraestructura?", "tipo": "si_no"},
        {"pregunta": "Observaciones adicionales (opcional)", "tipo": "texto"}
    ],
    "Hardware": [
        {"pregunta": "¿Todos los equipos del laboratorio están etiquetados con código patrimonial?", "tipo": "si_no"},
        {"pregunta": "Cantidad de computadoras operativas", "tipo": "numero"},
        {"pregunta": "¿Se realiza mantenimiento preventivo?", "tipo": "si_no"},
        {"pregunta": "Frecuencia de mantenimiento", "tipo": "multiple", "opciones": ["Mensual", "Trimestral", "Semestral", "Nunca"]},
        {"pregunta": "¿Existen computadoras con fallas conocidas?", "tipo": "si_no"},
        {"pregunta": "¿Se revisan los ventiladores internos?", "tipo": "si_no"},
        {"pregunta": "Estado general del hardware", "tipo": "escala"},
        {"pregunta": "¿Hay impresoras instaladas en el laboratorio?", "tipo": "si_no"},
        {"pregunta": "Cantidad de monitores funcionales", "tipo": "numero"},
        {"pregunta": "¿Existen teclados o ratones dañados?", "tipo": "si_no"},
        {"pregunta": "¿Las computadoras cuentan con al menos 8GB de RAM?", "tipo": "si_no"},
        {"pregunta": "¿Hay hardware obsoleto?", "tipo": "si_no"},
        {"pregunta": "¿Existen equipos de red (routers, APs) que funcionan?", "tipo": "si_no"},
        {"pregunta": "¿Se cuenta con un inventario actualizado de hardware?", "tipo": "si_no"},
        {"pregunta": "¿El hardware cumple con los requerimientos de las materias impartidas?", "tipo": "si_no"},
        {"pregunta": "Tipo de procesador promedio", "tipo": "multiple", "opciones": ["Intel i3", "i5", "i7", "AMD Ryzen", "Otro"]},
        {"pregunta": "¿Se utilizan SSDs o discos mecánicos?", "tipo": "multiple", "opciones": ["Solo SSD", "Solo HDD", "Ambos", "No sabe"]},
        {"pregunta": "¿Los equipos presentan problemas de temperatura?", "tipo": "si_no"},
        {"pregunta": "¿Hay dispositivos de respaldo como NAS o discos externos?", "tipo": "si_no"},
        {"pregunta": "¿La BIOS de los equipos está actualizada?", "tipo": "si_no"},
        {"pregunta": "¿Se ha identificado hardware clonado o irregular?", "tipo": "si_no"},
        {"pregunta": "¿Existen tarjetas de red adicionales instaladas?", "tipo": "si_no"},
        {"pregunta": "¿Las fuentes de poder son de buena calidad?", "tipo": "escala"},
        {"pregunta": "¿Qué antigüedad tienen los equipos?", "tipo": "multiple", "opciones": ["<1 año", "1-3 años", "3-5 años", ">5 años"]},
        {"pregunta": "¿Hay equipos con BIOS protegida por contraseña?", "tipo": "si_no"},
        {"pregunta": "Observaciones adicionales", "tipo": "texto"}
    ],

    "Software": [
        {"pregunta": "¿Todos los equipos tienen sistema operativo legal?", "tipo": "si_no"},
        {"pregunta": "Sistema operativo principal instalado", "tipo": "multiple", "opciones": ["Windows 10", "Windows 11", "Linux", "Otro"]},
        {"pregunta": "¿Hay actualizaciones automáticas activadas?", "tipo": "si_no"},
        {"pregunta": "¿Existen licencias de antivirus vigentes?", "tipo": "si_no"},
        {"pregunta": "¿El software educativo instalado es suficiente?", "tipo": "escala"},
        {"pregunta": "¿Se utiliza algún sistema de gestión de clases (LMS)?", "tipo": "si_no"},
        {"pregunta": "¿Se realiza respaldo de información de usuarios?", "tipo": "si_no"},
        {"pregunta": "¿Se hace limpieza de software innecesario?", "tipo": "si_no"},
        {"pregunta": "¿Los equipos tienen software de auditoría instalado?", "tipo": "si_no"},
        {"pregunta": "¿Existe control de licencias de software?", "tipo": "si_no"},
        {"pregunta": "¿Se han identificado programas piratas?", "tipo": "si_no"},
        {"pregunta": "Software para programación instalado", "tipo": "multiple", "opciones": ["VS Code", "PyCharm", "Eclipse", "Ninguno", "Otro"]},
        {"pregunta": "¿Hay restricciones de navegación en los equipos?", "tipo": "si_no"},
        {"pregunta": "¿Los navegadores están actualizados?", "tipo": "si_no"},
        {"pregunta": "¿Se utilizan imágenes base para instalación?", "tipo": "si_no"},
        {"pregunta": "¿El software de oficina está completo?", "tipo": "si_no"},
        {"pregunta": "¿Los estudiantes pueden instalar software?", "tipo": "si_no"},
        {"pregunta": "¿Qué software específico usa la carrera de Informática?", "tipo": "texto"},
        {"pregunta": "Frecuencia de actualización del software", "tipo": "multiple", "opciones": ["Mensual", "Semestral", "Anual", "Nunca"]},
        {"pregunta": "Observaciones sobre legalidad del software", "tipo": "texto"}
    ],

    "Seguridad": [
        {"pregunta": "¿Las computadoras están ancladas o aseguradas físicamente?", "tipo": "si_no"},
        {"pregunta": "¿Hay cámaras de seguridad en el laboratorio?", "tipo": "si_no"},
        {"pregunta": "¿Existe un control de acceso al laboratorio?", "tipo": "si_no"},
        {"pregunta": "¿Solo personal autorizado puede ingresar?", "tipo": "si_no"},
        {"pregunta": "¿Los equipos están protegidos contra picos eléctricos?", "tipo": "si_no"},
        {"pregunta": "¿Hay software de seguridad instalado?", "tipo": "si_no"},
        {"pregunta": "¿Hay firewalls activados en los equipos?", "tipo": "si_no"},
        {"pregunta": "¿Existe plan de respuesta ante incidentes?", "tipo": "si_no"},
        {"pregunta": "¿Se realizan auditorías de seguridad?", "tipo": "si_no"},
        {"pregunta": "¿Los usuarios tienen contraseñas seguras?", "tipo": "si_no"},
        {"pregunta": "¿Se ha detectado acceso no autorizado?", "tipo": "si_no"},
        {"pregunta": "¿Se utilizan políticas de seguridad?", "tipo": "si_no"},
        {"pregunta": "¿Los usuarios se autentican con cuentas propias?", "tipo": "si_no"},
        {"pregunta": "¿Hay señalización de seguridad visible?", "tipo": "si_no"},
        {"pregunta": "¿Existen extintores cerca del laboratorio?", "tipo": "si_no"},
        {"pregunta": "¿Hay un sistema de monitoreo centralizado?", "tipo": "si_no"},
        {"pregunta": "¿Existen logs de acceso físico o lógico?", "tipo": "si_no"},
        {"pregunta": "¿Los switches y routers están en gabinetes cerrados?", "tipo": "si_no"},
        {"pregunta": "¿Se han presentado robos o pérdidas?", "tipo": "si_no"},
        {"pregunta": "¿Se realiza backup regularmente?", "tipo": "si_no"},
        {"pregunta": "¿El personal está capacitado en seguridad?", "tipo": "si_no"},
        {"pregunta": "¿Existen políticas de seguridad firmadas?", "tipo": "si_no"},
        {"pregunta": "Observaciones sobre seguridad física o lógica", "tipo": "texto"}
    ],

    "Entorno físico": [
        {"pregunta": "¿El ambiente cuenta con buena iluminación?", "tipo": "si_no"},
        {"pregunta": "¿Hay ventilación adecuada?", "tipo": "si_no"},
        {"pregunta": "¿El espacio es suficiente para 30 estudiantes?", "tipo": "si_no"},
        {"pregunta": "¿Los pisos están en buen estado?", "tipo": "si_no"},
        {"pregunta": "¿Se realiza limpieza regularmente?", "tipo": "si_no"},
        {"pregunta": "¿Hay presencia de insectos o roedores?", "tipo": "si_no"},
        {"pregunta": "¿El ambiente tiene ventanas con protección?", "tipo": "si_no"},
        {"pregunta": "¿El ruido ambiental afecta el trabajo?", "tipo": "si_no"},
        {"pregunta": "¿Las paredes están en buen estado?", "tipo": "si_no"},
        {"pregunta": "¿La iluminación es natural o artificial?", "tipo": "multiple", "opciones": ["Natural", "Artificial", "Ambas"]},
        {"pregunta": "¿Se controla la temperatura en el aula?", "tipo": "si_no"},
        {"pregunta": "¿El lugar es accesible para personas con discapacidad?", "tipo": "si_no"},
        {"pregunta": "¿Se cuenta con señalización de emergencia?", "tipo": "si_no"},
        {"pregunta": "¿El mobiliario está bien distribuido?", "tipo": "si_no"},
        {"pregunta": "¿Hay áreas restringidas claramente delimitadas?", "tipo": "si_no"},
        {"pregunta": "Observaciones sobre el entorno físico", "tipo": "texto"}
    ],

    "Mobiliario y equipo": [
        {"pregunta": "¿Las mesas están en buen estado?", "tipo": "si_no"},
        {"pregunta": "¿Las sillas son ergonómicas?", "tipo": "si_no"},
        {"pregunta": "¿Hay suficientes sillas para todos los usuarios?", "tipo": "si_no"},
        {"pregunta": "¿Existen muebles de almacenamiento?", "tipo": "si_no"},
        {"pregunta": "¿El mobiliario presenta desgaste excesivo?", "tipo": "si_no"},
        {"pregunta": "¿Las estaciones de trabajo tienen el espacio adecuado?", "tipo": "si_no"},
        {"pregunta": "¿Hay escritorios con altura regulable?", "tipo": "si_no"},
        {"pregunta": "¿El mobiliario interfiere con la circulación?", "tipo": "si_no"},
        {"pregunta": "¿Existen mesas especiales para equipos de red?", "tipo": "si_no"},
        {"pregunta": "¿El mobiliario ha sido renovado recientemente?", "tipo": "si_no"},
        {"pregunta": "¿Se permite mover mobiliario libremente?", "tipo": "si_no"},
        {"pregunta": "¿Se han registrado accidentes por mobiliario?", "tipo": "si_no"},
        {"pregunta": "¿El mobiliario cumple normativas de seguridad?", "tipo": "si_no"},
        {"pregunta": "Observaciones sobre el mobiliario", "tipo": "texto"}
    ],
    
}
